default:
  image: docker:24.0.9
  services:
    - name: docker:24.0.9-dind
  before_script:
    - docker info

variables:
  DOCKER_TLS_CERTDIR: "/certs"

build:
  stage: build
  script:
    - docker login -u $SCCS_REGISTRY_USER -p $SCCS_REGISTRY_TOKEN $SCCS_REGISTRY
    - docker build -t $SCCS_REGISTRY/sccs/cygnet/cygnet:latest .
    - docker push $SCCS_REGISTRY/sccs/cygnet/cygnet:latest

