version: '3.4'

services:
  cygnet:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    # mount current dir inside container
    volumes:
      - .:/usr/src/app
      - ./photos:/usr/src/app/public/photos
    environment:
      NODE_ENV: development
      DOMAIN: http://localhost:3000
      KEYCLOAK_ID: "rsdv2"
      KEYCLOAK_ISSUER: "https://auth.sccs.swarthmore.edu/realms/master"
      NEXTAUTH_URL: "http://localhost:3000"
      DATABASE_URL: "mysql://root:S3cret@cygnet-db:3306/cygnet_db"
    env_file:
      - .env
    ports:
      - 3000:3000
    command: sh -c "npm install && npx prisma generate && npm run dev "

  cygnet-db:
    image: mariadb:11.3
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=cygnet_user
      - MYSQL_DATABASE=cygnet_db
