version: '3.4'

services:
  cygnet:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    # mount current dir inside container
    volumes:
      - .:/usr/src/app
      - ./photos:/usr/src/app/public/photos
    environment:
      NODE_ENV: development
      DOMAIN: http://localhost:3000
    env_file:
      - .env
    ports:
      - 3000:3000
    command: sh -c "npm install && npm run dev "
