import Nav from '@/components/nav'
import './globals.css'

export const metadata = {
  title: 'Cygnet',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) { 
  return (
    <html lang="en">
      <body className="bg">
        <Nav />
        <div className="container mont">
          {children}
        </div>
      </body>
    </html>
  )
}
