import Nav from '@/components/nav'
import './globals.css'
import Script from 'next/script'
import { NextAuthProvider } from './NextAuthProvider';
import Footer from '@/components/footer';

export const metadata = {
    title: 'Cygnet',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <NextAuthProvider>
            <html lang="en">
                <body className="bg">
                    <div className="most-height">
                        <Nav />
                        <div className="">
                            {children}
                        </div>
                    </div>
                    <Footer/>
                </body>
                {/*@ts-ignore*/}
                <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossOrigin="anonymous" />
                <Script src="https://kit.fontawesome.com/3d9fad96a7.js" crossOrigin="anonymous" />
            </html>
        </NextAuthProvider>
    )
}
