import Nav from '@/components/nav'
import './globals.css'
import Script from 'next/script'
import { NextAuthProvider } from './NextAuthProvider';
import Footer from '@/components/footer';
import { mont } from './fonts';

export const metadata = {
    title: 'Cygnet',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <NextAuthProvider>
            <html lang="en" className={`${mont.className} font-medium`}>
                <body className="bg-page-bg-light dark:bg-page-bg-dark">
                    <div className="most-height">
                        <Nav />
                        <div className="">
                            {children}
                        </div>
                    </div>
                    <Footer/>
                </body>
                <Script src="https://kit.fontawesome.com/3d9fad96a7.js" crossOrigin="anonymous" />
            </html>
        </NextAuthProvider>
    )
}
